filetype off
let &runtimepath .= ',' . expand('<sfile>:p:h:h')
let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/vader.vim'
echom &runtimepath
filetype plugin indent on
syntax enable

let g:floaterm_type          = 'floating'
let g:floaterm_keymap_new    = '<F7>'
let g:floaterm_keymap_prev   = '<F8>'
let g:floaterm_keymap_next   = '<F9>'
let g:floaterm_keymap_toggle = '<F12>'
