set nocompatible

filetype off

let &runtimepath .= ',' . expand('<sfile>:p:h:h')
if $USER == 'runner'
  let g:run_in_ci = v:true
  let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/vader.vim'
  let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/Leaderf-floaterm'
  let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/fzf-floaterm'
  let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/asyncrun.vim'
  let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/asyncrun.extra'
else
  let g:run_in_ci = v:false
  let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/../vader.vim'
  " let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/../Leaderf-floaterm'
  " let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/../fzf-floaterm'
  " let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/../asyncrun.vim'
  " let &runtimepath .= ',' . expand('<sfile>:p:h:h') . '/../asyncrun.extra'
endif

" NOTE: echom will frozen vim8 in GitHub Action
" echom &runtimepath

filetype plugin indent on
syntax enable

let g:mapleader = ';'
nnoremap <silent>       Q         :qa!<CR>
nnoremap <silent> <Leader>m :messages<CR>
